version: '3'
services:
  database:
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      timeout: 2s
      retries: 100

  backend:
    image: kimmingyu0/backend:${TAG:-latest}
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}

  frontend:
    image: kimmingyu0/frontend:0.0.1-SNAPSHOT
    ports:
      - "80:80"
