name: deploy

on:
  repository_dispatch:
    types: [deploy-service]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE: ${{ github.event.client_payload.service }}
      TAG: ${{ github.event.client_payload.tag }}

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
      
      - name: Docker Hub 로그인
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Pull Docker image
        run: |
          IMAGE="kimmingyu0/${SERVICE}:${TAG}"
          echo "Pulling $IMAGE"
          docker pull $IMAGE

      - name: Restart container
        run: |
          COMPOSE_FILE="/home/ubuntu/react_sb_board/docker/docker-compose.yml"
          echo "재시작 서비스: $SERVICE"
          docker compose -f $COMPOSE_FILE up -d $SERVICE --remove-orphans --wait

      - name: 배포 완료 로그
        run: |
          echo "배포 완료: $SERVICE $TAG"
        
